### ISSUE TITLE
Server-side use

### ISSUE THREAD

**Issue by jmaxdp** [superRaytin/image-clipper#2]
Problem 1: Even with canvas set I get "window is undefined"
problem 1 workaround: global.window = electron.mainwindow;

Problem 2: Uncaught Exception: TypeError: Image is not a constructor

global.window = mainWindow;
    const imageToSlices = require('image-to-slices');

    imageToSlices.configure({
      clipperOptions: {
        canvas: require('canvas')
      }
    });

    const lineXArray = [100, 200];
    const lineYArray = [100, 200];
    const source = './myimage.jpg'; // width: 300, height: 300

    imageToSlices(source, lineXArray, lineYArray, {
      saveToDir: './'
    }, () => {
      console.log('the source image has been sliced into 9 sections!');
    });

Please help or give more instruction on Server-side node js. I want to slice up an image and place the slices in the same directory.

Thanks

**Comment by superRaytin** [comment]
Pls try to upgrade to `0.4.4`
